# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IsNE0KVkix2erkh4L9l1A0viSYwmJA60
"""

def fib_rec(n):  # Рекурсионная функция для поиска числа фибоначчи
  if n==1:
    return 0
  elif n==2:
    return 1
  else:
    return (fib(n-1) + fib(n - 2))

def fib_std(n):  # Обычная функция для поиска числа фибоначчи
  result = [0,1]
  for i in range(2,n+1):
    result.append(result[i-2]+result[i-1])
  return result.pop()



numb = int(input("Vvedi chislo\n")) # Берем число с клавиатуры
print(fib_rec(numb) if numb <= 30 else fib_std(numb)) #Ищем numb число последовательности Фибоначчи
# рекурсивной фнукцией если значение 30 и меньше и обычной иначе, чтобы не грузить процессор на бесконечное выполнение